# Ganti dengan password admin kamu
ADMIN_PASSWORD = "qotrunnada"

# Kunci AES-128 dalam hex (32 digit).
AES128_KEY_HEX = "00112233445566778899aabbccddeeff"
import os

st.caption(f"Lokasi DB: {os.path.abspath(DB_PATH)}")
if os.path.exists(DB_PATH):
    with open(DB_PATH, "rb") as f:
        st.download_button(
            "⬇️ Unduh Database (SQLite)",
            data=f,
            file_name="submissions.db",
            mime="application/octet-stream"
        )
else:
    st.warning("Database belum terbentuk (belum ada kiriman).")
